#!/bin/ksh
displayDocumentation ()
{
/bin/echo "Change Log:"
/bin/echo "----------:"
/bin/echo "2015/12/14: allow for two space-separated values to be supplied"
/bin/echo "            in a \"bypass check\" field, the first value will be"
/bin/echo "            the routine name to be executed; the second, optional"
/bin/echo "            value will be an argument passed to the routine - the"
/bin/echo "            bypass check will determine whether a given parameter"
/bin/echo "            file line is processed or bypassed (new parameter field)"
/bin/echo ""
/bin/echo "Script nscaDirectory information and usage:"
/bin/echo "-------------------------------------------"
/bin/echo " 1. monitors directory utilization for Linux systems only"
/bin/echo "    (file count and disk space)"
/bin/echo " 2. communicates with Nagios via NSCA"
/bin/echo "    (NSCA daemon and configuration file must be present in the"
/bin/echo "     home directory of the executing user or in /usr/local/bin,"
/bin/echo "     else the script will exit)"
/bin/echo " 3. if the executing user's home directory contains a non-null file"
/bin/echo "    named \"nscaTarget.dta\", the value in that file is used as the"
/bin/echo "    destination for NSCA data, else \"monitor1.wpprivate.com\" is"
/bin/echo "    used (nscaTarget.dta content should be the IP of monitor1 or"
/bin/echo "    another Nagios server)"
/bin/echo " 4. execution requires presence one parm file named \"directory.dta\""
/bin/echo "    in the executing user's home directory,"
/bin/echo " 5. each parameter file line consists of 6 pipe-delimited fields:"
/bin/echo "           directory  - the directory to monitor"
/bin/echo "          thresholds  - if supplied, a comma-delimited string which"
/bin/echo "                        may specify threshold values"
/bin/echo "                        Valid threshold parameter options:"
/bin/echo "                           mbWarn     mbCrit"
/bin/echo "                           countWarn  countCrit"
/bin/echo "                           noPerfData (no Nagios performance data)"
/bin/echo "                                      (i.e., no data to Graphite)"
/bin/echo "                        Examples:"
/bin/echo "                           mbWarn=20"
/bin/echo "                           countCrit=500"
/bin/echo "                           countWarn=100,mbCrit=50"
/bin/echo "                           mbWarn=30,countCrit=1000,noPerfData"
/bin/echo "    hostname override - if the target Nagios host is something other"
/bin/echo "                        than the local hostname, supply the target"
/bin/echo "                        Nagios host value here"
/bin/echo "         servicegroup - the desired Nagios \"servicegroup\""
/bin/echo "                        association for this process - if blank"
/bin/echo "                        or invalid (not known to Nagios), the"
/bin/echo "                        default servicegroup assocation for this"
/bin/echo "                        host will be used"
/bin/echo "               exempt - (optional) name pattern to be exluded from"
/bin/echo "                        the file count (but not the total of file"
/bin/echo "                        sizes); this value may contain a leading OR"
/bin/echo "                        trailing asterisk for a \"wild-card\" match"
/bin/echo "                        (if asterisk is used, the exempt value must"
/bin/echo "                        be surrounded by double-quotes)"
/bin/echo "         bypass check - if used, this value must be the name of a"
/bin/echo "                        routine in the executing user's home"
/bin/echo "                        directory used to determine whether or not"
/bin/echo "                        this particular process check (for string 1,"
/bin/echo "                        and string 2, if present) should be"
/bin/echo "                        bypassed; the routine must \"echo\" out"
/bin/echo "                        a value of YES, Yes, or yes (to bypass the"
/bin/echo "                        check, or NO, No, or no (to execute the"
/bin/echo "                        checkin - for example:"
/bin/echo "                        if a process should always be running except"
/bin/echo "                        when something else is running (like a"
/bin/echo "                        cold backup), then a bypass check routine"
/bin/echo "                        could be used to determine if that"
/bin/echo "                        \"something else\" is running or not; if so"
/bin/echo "                        the routine can output a \"yes\" (to bypass"
/bin/echo "                        the check) or \"no\" to NOT bypass and do"
/bin/echo "                        the check"
/bin/echo " 6. accepts \"debug\" argument (value \"debug\", case insensitive)"
/bin/echo "    to trace logic performed by the script and disable transmission"
/bin/echo "    of data to Nagios"
/bin/echo " 7. accepts \"tries=n\" argument (case insensitive) to be used"
/bin/echo "    as the \"max_check_attempts\" value in the auto-deployed"
/bin/echo "    Nagios service (if not supplied, default is 1)"
/bin/echo "    Explanation - if there are warning and/or critical thresholds"
/bin/echo "    in effect for this monitor, and if the warning/critical action"
/bin/echo "    (email/alert) should occur immediately upon a threshold being"
/bin/echo "    met/exceeded, then don't supply this argument, or supply"
/bin/echo "    \"tries=1\". However, if you want a threshold-met/exceeded"
/bin/echo "    condition to persist for some duration before action is taken,"
/bin/echo "    then use this argument to define the desired duration."
/bin/echo "    The \"duration\" is actually the number of consecutive times"
/bin/echo "    the Nagios service must be set to a WARNING or CRITICAL state"
/bin/echo "    in order to trigger an action. For example, if this script"
/bin/echo "    is run every five minutes and a non-OKAY condition must"
/bin/echo "    persist for ten minutes before notification takes place,"
/bin/echo "    then use \"tries=3\":"
/bin/echo "    a. problem state onset occurs - Nagios check attempts=1"
/bin/echo "    b. 5 minutes later, problem state persists - check attempts=2"
/bin/echo "    c. 5 minutes later, problem state persists - check attempts=3,"
/bin/echo "       action (email/alert) is triggered"
/bin/echo " 8. script will exit if a StopAllMonitoring (case insensitive) file"
/bin/echo "    is encountered in /var/tmp"
/bin/echo " 9. the script attempts to find the local hostname first in a file"
/bin/echo "    named Nagios_hostname.dta in the executing user's home"
/bin/echo "    directory, else the \"uname -n\" command is used"
/bin/echo "    (also see \"hostname override\" above)"
/bin/echo "10. for hosts/services not manually established in Nagios"
/bin/echo "    configuration, the first execution will trigger auto-deployment"
/bin/echo "    of the needed Nagios object(s) - to re-trigger auto-deployment,"
/bin/echo "    remove the \"NagiosServiceSetupTriggered_Directory\" file"
/bin/echo "    from the executing user's home directory (auto-deployment is"
/bin/echo "    also re-triggered by a change to directory-monitoring parameter"
/bin/echo "    input)"
/bin/echo "11. if expected execution results are not observed, check the"
/bin/echo "    contents of the \"nscaDirectory_lastStatus\" file in the executing"
/bin/echo "    user's home directory"
exit 0
}
#
toNagios ()
{
if [ $debugSw = yes ]
then
   /bin/echo "##### toNagios #####"
   set -x
fi
#
if [ $serviceSetup = No ]
then
#  Nagios service setup not triggered with this script execution
   targetHost=$nagiosHost
   nagiosSvc="Directory: ${directory}"
else
#  Nagios service setup triggered with this script execution (first time)
   targetHost=$nscaTarget
   nagiosSvc="Service Setup Capture"
   exitCode=1
   if [ "$capturedSvc" = "" ]
   then
      capturedSvc="Directory: ${directory}"
   fi
   nagiosMsg="Directory@${nagiosHost}@${nagiosHostType}@${serviceGroup}@${capturedSvc}@${tries}@@@"
   capturedSvc=""
fi
nscaPkt="${targetHost}${tab}${nagiosSvc}${tab}${exitCode}${tab}${nagiosMsg}"
if [ "$debugSw" = "no" ]
then
   /bin/echo "$nscaPkt" | $nscaBinaryPath $nscaTarget -c $nscaConfigPath > /dev/null 2>&1
else
   /bin/echo "$nscaPkt"
fi
}
#
thresholdCheck ()
{
exitCode=0
for thresholdType in mbWarn countWarn mbCrit countCrit
do
   case $thresholdType in
      mbWarn)    threshold=$mbWarnThresh
                 metric=$MbUsed
                 statCode=1 ;;
      countWarn) threshold=$countWarnThresh
                 metric=$fileCount
                 statCode=1 ;;
      mbCrit)    threshold=$mbCritThresh
                 metric=$MbUsed
                 statCode=2 ;;
      countCrit) threshold=$countCritThresh
                 metric=$fileCount
                 statCode=2 ;;
   esac
   if [ $threshold != X ]
   then
      if [ $(/bin/echo "${metric}>=${threshold}" | /usr/bin/bc) -gt 0 ]
      then
         exitCode=$statCode
      fi
   fi
done
}
#
perfDataCheck ()
{
if [ "$debugSw" = "yes" ]
then
   /bin/echo "##### perfDataCheck #####"
   set -x
fi
#
/bin/echo $threshInput | /bin/grep noPerfData > /dev/null
if [ $? -eq 0 ]
then
   perfData=No
   threshInput=$(/bin/echo $threshInput | /bin/sed 's/noPerfData//g' | /bin/sed 's/,,/,/g')
fi
}
#
setupThresholds ()
{
mbWarnThresh=X
mbCritThresh=X
countWarnThresh=X
countCritThresh=X
IFS=" "
threshInput=$(/bin/echo $threshInput | /bin/sed 's/,/ /g')
for argNum in $threshInput
do
   argType=$(/bin/echo $argNum | $cut -f1 -d"=")
   case $argType in
      mbCrit) mbCritThresh=$(/bin/echo $argNum | $cut -f2 -d"=") ;;
      mbWarn) mbWarnThresh=$(/bin/echo $argNum | $cut -f2 -d"=") ;;
      countCrit) countCritThresh=$(/bin/echo $argNum | $cut -f2 -d"=") ;;
      countWarn) countWarnThresh=$(/bin/echo $argNum | $cut -f2 -d"=") ;;
   esac
done
#
if [ "$threshInput" != "" ]
then
   threshDisp=$(/bin/echo $threshInput | /bin/sed 's/ /,/g')
   threshDisp=", thresholds: ${threshDisp}"
else
   threshDisp=""
fi
}
#
processExemptArg ()
{
if [ "$debugSw" = "yes" ]
then
   /bin/echo "############################"
   /bin/echo "##### processExemptArg #####"
   /bin/echo "############################"
   set -x
fi
#
wildCardSw=No
wildCardPrefix=""
wildCardSuffix=""
/bin/echo "$exemptArg" | /bin/grep "\*" > /dev/null
if [ $? -eq 0 ]
then
   wildCardSw=Yes
   wildCardWork=$(/bin/echo ${exemptArg} | /bin/sed 's/\*/|/' | /bin/sed 's/\"//g')
   oldIFS="$IFS"
   IFS="|"
   set -- $wildCardWork
   wildCardPrefix=$1
   wildCardSuffix=$2
   IFS="$oldIFS"
else
   exemptArg=$(/bin/echo ${exemptArg} | /bin/sed 's/"//g')
fi
}
#
serviceLoop ()
{
if [ "$debugSw" = "yes" ]
then
   /bin/echo "#######################"
   /bin/echo "##### serviceLoop #####"
   /bin/echo "#######################"
   set -x
fi
#
for dirLine in `/bin/cat $parmFile`
do
   oldIFS="$IFS"
   IFS="|"
   set -- $dirLine
   directory=$1
   overrideHost=$3
   bypassCheck=$6
   IFS=" "
   set -- $bypassCheck
   bypassCheck=$1
   bypassCheckArg=$2
   IFS="$oldIFS"
   if [ "$bypassCheck" = " " -o "$bypassCheck" = "" ]
   then
      bypassSw=No
   else
      /usr/bin/test -s ${homeDir}/${bypassCheck}
      if [ $? -eq 0 ]
      then
         bypassSw=$(${homeDir}/${bypassCheck} ${bypassCheckArg})
      else
         bypassSw=No
      fi
   fi
   case $bypassSw in
      NO|No|no)
         if [ "$overrideHost" != "" ]
         then
            nagiosHost=$overrideHost
         fi
         toNagios ;;
   esac
done
exit 0
}
#
initializeServiceCapture ()
{
if [ "$debugSw" = "yes" ]
then
   /bin/echo "####################################"
   /bin/echo "##### initializeServiceCapture #####"
   /bin/echo "####################################"
   set -x
fi
#
initializeHostsFile=/tmp/nscaDirectory_initializeHosts
/bin/cat /dev/null > $initializeHostsFile
for parmLine in `/bin/cat ${parmFile}`
do
   oldIFS="$IFS"
   IFS="|"
   set -- $parmLine
   nagiosHostOverride=$3
   bypassCheck=$6
   IFS=" "
   set -- $bypassCheck
   bypassCheck=$1
   bypassCheckArg=$2
   IFS="$oldIFS"
   if [ "$bypassCheck" = " " -o "$bypassCheck" = "" ]
   then
      bypassSw=No
   else
      /usr/bin/test -s ${homeDir}/${bypassCheck}
      if [ $? -eq 0 ]
      then
         bypassSw=$(${homeDir}/${bypassCheck} ${bypassCheckArg})
      else
         bypassSw=No
      fi
   fi
   case $bypassSw in
      NO|No|no)
         if [ "$nagiosHostOverride" = "" ]
         then
            nagiosHostOverride=$saveNagiosHost
         fi
         hostOverrideArg="|${nagiosHostOverride}|"
         /bin/grep "$hostOverrideArg" $initializeHostsFile > /dev/null
         if [ $? -ne 0 ]
         then
            /bin/echo "$hostOverrideArg" >> $initializeHostsFile
            nagiosHost=$nagiosHostOverride
            capturedSvc="ACCUMULATE START"
            toNagios
            /bin/sleep 2
         fi ;;
    esac
done
/bin/sleep 10
}
#
noBypass()
{
if [ "$debugSw" = "yes" ]
then
   /bin/echo "####################"
   /bin/echo "##### noBypass #####"
   /bin/echo "####################"
   set -x
fi
#
if [ "$overrideHost" != "" ]
then
   nagiosHost=$overrideHost
fi
if [ "$serviceGroup" = "" ]
then
   serviceGroup=APPNAME
fi
perfData=Yes
perfDataCheck
setupThresholds
if [ "$exemptArg" = "" ]
then
   fileCount=$(/usr/bin/find ${directory} -type f | /usr/bin/wc -l | /bin/sed 's/ //g')
else
   processExemptArg
   if [ $wildCardSw = Yes ]
   then
      fileCount=$(/usr/bin/find ${directory} -name "${wildCardPrefix}*${wildCardSuffix}" -prune -o -print | /usr/bin/wc -l | /bin/sed 's/ //g')
   else
      fileCount=$(/usr/bin/find ${directory} -name ${exemptArg} -prune -o -print | /usr/bin/wc -l | /bin/sed 's/ //g')
   fi
fi
unitsUsed=$(/usr/bin/du -bc $directory | /usr/bin/tail -n 1 | $awk '{print $1}')
# Linux "du -bc" shows space in bytes
# There are 1048576 bytes per MB
MbUsed=$(/bin/echo ${unitsUsed} | $awk '{printf "%6.2f",($1/1048576)}' | /bin/sed 's/ //g')
thresholdCheck
case $exitCode in
   0) status=OK ;;
   1) status=WARNING ;;
   2) status=CRITICAL ;;
esac
msg="FileCount=${fileCount} UsedMb=${MbUsed}"
if [ $perfData = Yes ]
then
   nagiosMsg="Directory ${status}: ${msg}${threshDisp} | twpDirectory ${status} ${msg}"
else
   nagiosMsg="Directory ${status}: ${msg}${threshDisp}"
fi
toNagios
}
#
/usr/bin/test -f /bin/awk
if [ $? -eq 0 ]
then
   awk=/bin/awk
else
   awk=/usr/bin/awk
fi
/usr/bin/test -f /bin/cut
if [ $? -eq 0 ]
then
   cut=/bin/cut
else
   cut=/usr/bin/cut
fi
#
tries=1
debugSw=no
IFS="
"
for inputArg in $1 $2 $3
do
   /bin/echo "$inputArg" | /bin/grep -i help > /dev/null
   if [ $? -eq 0 ]
   then
      displayDocumentation
   else
      /bin/echo "$inputArg" | /bin/grep -i debug > /dev/null
      if [ $? -eq 0 ]
      then
         /bin/echo " ##### Top of Mainline #####"
         debugSw=yes
         set -x
      else
         /bin/echo "$inputArg" | /bin/grep "tries=" > /dev/null
         if [ $? -eq 0 ]
         then
            oldIFS="$IFS"
            IFS="="
            set -- $inputArg
            tries=$2
            IFS="$oldIFS"
            triesHold=$(/bin/echo ${tries} | /bin/sed 's/[0-9]//g')
            if [ "$triesHold" != "" ]
            then
#              The tries value is not numeric, default to 1
               tries=1
            fi
         fi
      fi
   fi
done
#
owner=$(/usr/bin/whoami)
homeDir=$(/bin/grep ${owner} /etc/passwd | $cut -f6 -d":")
#
lastStatus=${homeDir}/nscaProcess_lastStatus
#
# Determine the path to the send_nsca and send_nsca.cfg modules, if any
nscaFound=No
for nscaDir in $homeDir /usr/local/bin /usr/local/nagios
do
   /usr/bin/test -s ${nscaDir}/send_nsca
   if [ $? -eq 0 ]
   then
      nscaBinaryPath=${nscaDir}/send_nsca
      /usr/bin/test -s ${nscaDir}/send_nsca.cfg
      if [ $? -eq 0 ]
      then
         nscaConfigPath=${nscaDir}/send_nsca.cfg
         nscaFound=Yes
         break
      fi
   fi
done
if [ $nscaFound = No ]
then
   /bin/echo "communication with Nagios not possible, NSCA binary not present" > $lastStatus
   exit 0
fi
#
/usr/bin/test -s ${homeDir}/nscaTarget.dta
if [ $? -eq 0 ]
then
   read nscaTarget < ${homeDir}/nscaTarget.dta
else
   nscaTarget=monitor1.wpprivate.com
fi
#
# Capture the name to use as the target host in Nagios from the
# ${homeDir}/Nagios_hostname.dta file, else use the "uname -n" command
/usr/bin/test -s ${homeDir}/Nagios_hostname.dta
if [ $? -eq 0 ]
then
   read nagiosHost < ${homeDir}/Nagios_hostname.dta
else
   nagiosHost=$(/bin/uname -n | $cut -f1 -d".")
fi
saveNagiosHost=$nagiosHost
#
exitCode=0
tab="	"
#
serviceSetup=No
#
parmFile=${homeDir}/directory.dta
/usr/bin/test -s $parmFile
if [ $? -eq 0 ]
then
#  The required input parameter file does exist with a non-zero size
   savedParms=/tmp/nscaDirectory_parmsSaved
   /usr/bin/test -s $savedParms
   if [ $? -eq 0 ]
   then
#     There is a saved copy of the parameter file, is it different from the
#     current version?
      /usr/bin/diff $parmFile $savedParms > /dev/null
      if [ $? -ne 0 ]
      then
#        The current and saved parameters are not the same, save the current
#        parameters and trigger Nagios service setup
         serviceSetup=Yes
         /bin/cat $parmFile > $savedParms
      fi
   else
#     There is not a saved copy of the parameter file; save it and trigger
#     Nagios service setup
      serviceSetup=Yes
      /bin/cat $parmFile > $savedParms
   fi
else
#  The required parameter file is null or absent, exit
   /bin/echo "required parm file ${parmFile} is absent or null, exiting" > $lastStatus
   exit 1
fi
#
# Check for existence of a StopAllMonitoring file in /var/tmp, if it exists,
# then bypass processing
ls /var/tmp | /bin/grep -i StopAllMonitoring > /dev/null
if [ $? -eq 0 ]
then
   nagiosMsg="StopAllMonitoring file encountered, exiting"
   /bin/echo "$nagiosMsg" > $lastStatus
   serviceLoop
fi
#
runCount=$(/bin/ps -ef | /bin/grep nscaDirectory | /bin/grep -v grep | /usr/bin/wc -l | /bin/sed 's/ //g')
if [ $runCount -gt 4 ]
then
   nagiosMsg="script backlog, nscaDirectory exiting, runCount: $runCount" > $lastStatus
   /bin/echo "$nagiosMsg" > $lastStatus
   serviceLoop
fi
#
# Has the number of Nagios check attempts changed?
savedTries=/tmp/nscaDirectory_tries_saved
/usr/bin/test -s $savedTries
if [ $? -eq 0 ]
then
   read savedTriesData < $savedTries
   if [ "$tries" != "$savedTriesData" ]
   then
#     The number of check attempts has changed
      serviceSetup=Yes
      /bin/echo "$tries" > $savedTries
   fi
else
   /bin/echo "$tries" > $savedTries
fi
#
serviceSetupFlag=${homeDir}/NagiosServiceSetupTriggered_Directory
/usr/bin/test -f $serviceSetupFlag
if [ $? -ne 0 ]
then
   /bin/touch $serviceSetupFlag
   serviceSetup=Yes
fi
#
if [ $serviceSetup = Yes ]
then
#  Trigger auto-deployment of Nagios service
   /usr/bin/test -s /etc/redhat-release
   if [ $? -eq 0 ]
   then
      /bin/grep CentOS /etc/redhat-release > /dev/null
      if [ $? -ne 0 ]
      then
         /bin/grep "Red Hat" /etc/redhat-release > /dev/null
         if [ $? -ne 0 ]
         then
            nagiosHostType=Unknown
         else
            nagiosHostType=RedHat
         fi
      else
         nagiosHostType=CentOS
      fi
   else
      /bin/uname -a | /bin/grep -i ubuntu > /dev/null
      if [ $? -eq 0 ]
      then
         nagiosHostType=Ubuntu
      else
         nagiosHostType=Unknown
      fi
   fi
   serviceSetup=Yes
   initializeServiceCapture
else
#  Nagios service setup previously triggered
   serviceSetup=No
fi
#
for directoryLine in `/bin/cat $parmFile`
do
   oldIFS="$IFS"
   IFS="|"
   set -- $directoryLine
   directory=$1
   threshInput=$2
   overrideHost=$3
   serviceGroup=$4
   exemptArg=$5
   bypassCheck=$6
   IFS=" "
   set -- $bypassCheck
   bypassCheck=$1
   bypassCheckArg=$2
   IFS="$oldIFS"
   if [ "$bypassCheck" = " " -o "$bypassCheck" = "" ]
   then
      bypassSw=No
   else
      /usr/bin/test -s ${homeDir}/${bypassCheck}
      if [ $? -eq 0 ]
      then
         bypassSw=$(${homeDir}/${bypassCheck} ${bypassCheckArg})
      else
         bypassSw=No
      fi
   fi
   case $bypassSw in
      NO|No|no) noBypass ;;
   esac
done
#
IFS="
"
if [ $serviceSetup = Yes ]
then
   nagiosHost=$saveNagiosHost
   for hostArg in `/bin/cat $initializeHostsFile`
   do
      nagiosHost=$(/bin/echo ${hostArg} | /bin/sed 's/|//g')
      capturedSvc="ACCUMULATE STOP"
      /bin/sleep 2
      toNagios
   done
   /bin/sleep 10
fi
#
